### ISSUE TITLE
Is validationNamesOfPredictions.cfg supposed to be the same as testNamesOfPredictions.cfg

### ISSUE THREAD

**Issue by poyukao** [Kamnitsask/deepmedic#3] opened 2016-06-08 22:49 UTC
Hello, 

In your dataForExamples folder, test folder contains pat001 and pat002, train folder contains pat005 and pat006, and validation contains pat0003 and pat0004. 

In your configFiles for deepMedicLess, the file 'deepmedic/examples/configFiles/deepMedicLess/train/validation/validationNameOfPredictions.cfg' shows:
pred_brats_2013_pat0001_1_hgg.nii.gz
pred_brats_2013_pat0002_1_hgg.nii.gz

This file is the same as another file 'deepmedic/examples/configFiles/deepMedicLess/test/testNamesOfPredictions.cfg' which also shows:
pred_brats_2013_pat0001_1_hgg.nii.gz
pred_brats_2013_pat0002_1_hgg.nii.gz

This issue also happens on other folders tinyCnn and deepMedic. 
Is validationNamesOfPredictions.cfg supposed to be the same as testNamesOfPredictions.cfg?

or should we change validationNameOfPredictions.cfg into:
pred_brats_2013_pat0003_1_hgg.nii.gz
pred_brats_2013_pat0004_1_hgg.nii.gz

and testNamesOfPredictions.cfg into:
pred_brats_2013_pat0001_1.nii.gz
pred_brats_2013_pat0002_1.nii.gz
without hgg in the end since you did not predict if this patient is hgg or lgg?

Thank you for your reply.

Best,
Po-Yu Kao

**Comment by Kamnitsask** [comment] 2016-06-09 14:13
Hello,

These Name-Of-Predictions.cfg files are there for the user to specify the names that the results (probability/segmentation/feature maps) will be saved with when generated for each patient.

Yes, you are right, seems like there are some inconsistencies there in the above mentioned files. Although since they are only for the naming of the results, and not for reading-purposes, the problem is rather minor. I will fix it in the next push nevertheless (soon, currently in the process of validating the changes).

ps: the _hgg thing is again, only for naming purposes, nothing to do with what is predicted or not.

Thanks again for the feedback Po-Yu.

Kostas

**Comment by poyukao** [comment] 2016-06-09 23:53
Hello Kostas,

Thank you for your reply. 

Best,
Po-Yu

**Comment by Kamnitsask** [comment] 2016-06-17 13:28
Fixed. Thanks again for feedback.

Closing.

**Closed by Kamnitsask** 2016-06-17 13:28 UTC
