### ISSUE TITLE
Running it on 2D data

### ISSUE THREAD

**Issue by ctaiz96** [Kamnitsask/deepmedic#88] opened 2017-10-09 19:03 UTC
Hi Kostas, 

I am using Deepmedic with 2D nifti images. I have changed the kernel sizes setting the third dimension to 1 (ie. size [3 3 1]) and my input images are of size  img: [512x512 uint16]

(all specifications:

           hdr: [1x1 struct]
      filetype: 2
    fileprefix: 'processed_nomask'
       machine: 'ieee-le'
           img: [512x512 uint16]
      original: [1x1 struct] )

But during training I got the following error:

Traceback (most recent call last):
  File "./deepMedicRun", line 134, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "/Documents/GitHub/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/Documents/GitHub/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1197, in do_training
    reflectImageWithHalfProbDuringTraining
  File "/Documents/GitHub/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 770, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
    reflectImageWithHalfProb = reflectImageWithHalfProbDuringTraining
  File "/Documents/GitHub/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 123, in actual_load_patient_images_from_filepath_and_return_nparrays
    roiMaskData = reflectImageArrayIfNeeded(reflectFlags, roiMaskData)
  File "/Documents/GitHub/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 59, in reflectImageArrayIfNeeded
    reflImageArray = imageArray[::stepsForReflectionPerDimension[0], ::stepsForReflectionPerDimension[1], ::stepsForReflectionPerDimension[2]]
  File "/usr/local/lib/python2.7/site-packages/numpy/core/memmap.py", line 335, in __getitem__
    res = super(memmap, self).__getitem__(index)
IndexError: too many indices for array

Do you know what is making it give this error?

Many thanks!
Carla

**Comment by Kamnitsask** [comment] 2017-10-11 15:28
Hello Carla,

I have not previously tested the code on 2D data. I dont think there would be too many changes needed to make it run, probably quite some reconfig of the meta-params though (2d kernels will have far less weights, so some metaparams like learning rate may be needed).

But there is at least one change needed, which is probably the cause of this problem of yours. The data of yours are 2D [x,y] and should be loaded as 3D [x,y,z], with unary 3rd dimension z=1.

The data is loaded in:
trainValidateTestVisualiseParallel.py -> actual_load_patient_images_from_filepath_and_return_nparrays(...)

look for the nib.load() calls and the following get_load() calls. Probably it will just be enough if you reshape the nparray returned by get_load to [-1,-1, 1] dimensions.

Let me know how this goes.

K

**Comment by ctaiz96** [comment] 2017-10-12 15:27
Hi Kostas! 
thanks for your answer! It proved very helpful and I got over this error by just writing a small function on the py script

def getload(img_proxy):
    image = img_proxy.get_data()
    if len(image.shape) != 3:
        image=np.expand_dims(image, axis=2)
    return image

and calling it wherever get_data() was called in the script.

However, when I attempt to train the model it now

 gives me the same 'NoneType' error as Zhou Huan is mentioning: 

Loading subject with 1st channel at: /Documents/GitHub/deepmedic/examples2/dataForExamples/brats2015TrainingData/train/brats_2013_pat0005_1/niftifile_trial.nii
An error has occured during the function execution
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 90, in run
    __result = __f(*__args)
  File "<string>", line 94, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
  File "<string>", line 52, in actual_load_patient_images_from_filepath_and_return_nparrays
NameError: global name 'getload' is not defined
Traceback (most recent call last):
  File "./deepMedicRun", line 134, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "/Documents/GitHub/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/Documents/GitHub/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1218, in do_training
    labelsForCentralOfSegmentsForSubepTrain] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable


I have double checked the data I am inputing (so far only one example) and all my areas, rois and gt lables have the same dimensions. Do you know if there could be something else which is causing this error? I have attached the info of the files in case you want to have a look at them (I am actually using the same file for rois and gt, a plain white square in a black background, since at this stage I just want to have the software run on the cases I am using. I wasn´t able to attach the nifti files, but I can send them via email if that is better.

Many thanks for your help!

Carla
<img width="1440" alt="bildschirmfoto 2017-10-12 um 16 25 54" src="https://user-images.githubusercontent.com/32650950/31504371-210711c8-af6a-11e7-8d31-cb1ae5135048.png">
<img width="1440" alt="bildschirmfoto 2017-10-12 um 16 25 35" src="https://user-images.githubusercontent.com/32650950/31504390-2a744942-af6a-11e7-85c3-69365b5ed766.png">

**Comment by Kamnitsask** [comment] 2017-10-12 21:47
Hello,

During the "do_training" routine, there is a parallel process being spawned at every iteration, that extracts the data for the next training batch. It's the "parallel python" aka "pp" package used for that, to check for documentation that will help for your debugging. When anything goes wrong at runtime during this process, it returns "None" instead of data for a batch. So, the problem is not the NoneType error, but what caused.

And what caused it, is reported in the error message, right before the "traceback" line. In this case, it says "NameError: global name 'getload' is not defined".

Which means that the parallel process does not know about your getload() function. You need to tell to pp that this new function will be used (see pp documentation).

Look for the variable "tupleWithLocalFunctionsThatWillBeCalledByTheMainJob", and add the name of your function in that tuple.

If any more debugging is used, please first check the error message given before the "traceback", roughly 10 lines above the NoneType error.

Hope this helps,
K

**Comment by ctaiz96** [comment] 2017-10-12 22:11
Thank you very much for the quick reply. And for indicating the actual error which I had completely missed. It is working perfectly now, both the training and the testing!

Best, 
Carla

**Comment by Kamnitsask** [comment] 2017-10-13 12:49
Glad to here. Let the issue open for a bit, I may try to integrate processing 2D data in the code more naturally soon.

K

**Comment by Kamnitsask** [comment] 2017-10-28 22:38
This is now supported in v0.6.1, currently on the branch supportTheano09, soon to be merged to master.

Thanks a lot ctaiz96 for feedback on this.

Closing.

**Closed by Kamnitsask** 2017-10-28 22:38 UTC

**Comment by joelthelion** [comment] 2019-03-14 16:15
Would anyone have a 2D model.cfg to share?

**Comment by sarthakpati** [comment] 2020-02-24 18:42
I'd also be interested in having an example 2D model config file. Cheers!
