### ISSUE TITLE
Some questions on whole flow

### ISSUE THREAD

**Issue by anewlearner** [Kamnitsask/deepmedic#26] opened 2016-10-19 14:10 UTC
Dear Kamnitsask,

Thanks for sharing your project. It’s really a great work. 
I’m very interested in it, and have some questions. Could you please help me?
1. You said that DeepMedic processes NIFTI files only. If I want to process other data format such as .mat file, is there a big change I should make in the source code?
2. In part 3.1. Model Creation, It seems to be 

> corresponding layer ([30, 40, 40, 50]

 instead of 

> corresponding layer ([15, 20, 25, 30]

.
3. In the trainConfig file, we need to specify the path of the training data (such as channelsTraining). How can I do to set multiple samples? For examples, in the tinnyCNN examples,`channelsTraining = ["./trainChannels_flair.cfg", "./trainChannels_t1c.cfg"]`. It is only one sample.
4. What is the strategy to get the predicted soft segmentation map of the whole image? For examples, sliding window.
5. In figure 1, the output of the last convolution layer of the double-pathway architecture is 50×9^3+50×9^3 (subsampling). How can it change to 150×9^3?

Thanks!

Carol

**Comment by Kamnitsask** [comment] 2016-10-26 10:28
Hello Carol,

First of all, thanks for your interest and your feedback. I m really thankful.

1. Currently, the library used for loading/saving images is "nibabel". All the *loading* is done in ./deepmedic/trainValidateTestVisualiseParallel.py. Specifically, all loading is inside the function `actual_load_patient_images_from_filepath_and_return_nparrays`. It should not be too difficult to change and load other formats if you know what you are doing. Look for the commands `nib.load(...)` that are usually followed by `.get_data()`. If you replace this with the loading interface of your choice, and make sure that the resulting array is a 3D array, then the rest of the code should work the same. Note that, if you introduce a new library for the loading, you ll have to tell the parallel job (pp library) that it has to import it. Look for line: `tupleWithModulesToImportWhichAreUsedByTheJobFunctions = (...)`

2. True, nice one. Will fix it in next push.

3. These files listed are 1 for each modality/channel. Not one for each subject/case/patient/sample. If you go and check each of these files, it's within them that you list each individual case/subject. In the examples I provided, 2 training cases are listed. For your data, in each of these "trainChannels_XXX.cfg" files, you ll have to add more rows, one for each subject.

4. The volume is tiled/broken up in smaller subvolumes, as big as the size of a "segment". You predict the central part (not voxel, multiple voxels) of each segment, then take the next, partially overlapping segment, predict, etc... Within each segment, the CNN is applied in a fully-convolutional way (ie, similar to sliding-window, if that's what you meant).

5. the 50+50 (subsampled) are indeed first concatenated, giving a "layer" of 100 FMs. However this "layer" is not depicted. The two depicted layers of 150 FMs are hidden layers with 150 FMs. ie, the first FC layer with 150 FMs is processing the concatenated 100 (50+50) FMs from the 2 pathways.

Hope the above explanations clear things up.

Kostas

**Comment by anewlearner** [comment] 2016-10-26 11:33
Hello Kostas,

Thanks for your reply. It helps a lot.

I'm not very clear about the third question.

> The volume is tiled/broken up in smaller subvolumes, as big as the size of a "segment". You predict the central part (not voxel, multiple voxels) of each segment, then take the next. Within each segment, the CNN is applied in a fully-convolutional way.

Assume that the size of the segment is 25×25×25, and the output of this segment is 9×9×9 after a fully-convolutional CNN. The pixel-wise prediction of the segment can be obtained by deconvolution(9×9×9->25×25×25) and there is no need to use overlapping segment. 

But it seem not to be the case here. Do you mean that the output(9×9×9) is just the prediction of the central part of the segment(the center 9×9×9 voxel of 25×25×25 segment ) and we need to use partially overlapping segment to get the prediction of the whole voxel?

Carol

**Comment by Kamnitsask** [comment] 2016-10-28 14:02
Hello again Carol,

I think you got it right in the last part of your reply ("But is seems...")

This is not the case where deconvolution would be useful, as the final 9x9x9 predictions are at the original resolution.

The configuration of the CNN in this example has a receptive field (RF) of (17^3) wrt the input. The CNN gives one prediction for each position that this RF can have over the input (25x25x25). At each possible position (when the RF is fully inside the input, never extending outside, eg as some people do when you use padding), you get a prediction for the central voxel of the RF. For a RF of 17^3, there are 9^3 such valid positions in the centre of a 25^3 input, and for these positions its that you get a segmentation in one forward pass.

To segment the whole volume, you tile it in segments (of 25^3 in this example). After you predict 9^3 central voxels of a 25^3 segment, you take another segment, 9 voxels further. The two segments will be partially overlapping.

Hope the above helps.
Kostas

**Comment by anewlearner** [comment] 2016-11-01 11:35
Hello Kostas,

Your explanation is great. Thanks for you help.

Carol

**Closed** 2016-11-01 13:08 UTC

**Comment by anewlearner** [comment] 2016-11-04 03:26
@Kamnitsask 

Sorry for disturbing you again.
I had some troubles in loading other data format.

As what you suggested, I changed loding part in `actual_load_patient_images_from_filepath_and_return_nparrays` to load .mat data(CT image) instead of NIFTI files.

For example,
```
fullFilenamePathOfChannel = listOfFilepathsToEachSubsampledChannelOfEachPatient[index_of_wanted_image][channel_i]
img_proxy = nib.load(fullFilenamePathOfChannel)
channelData = img_proxy.get_data()
img_proxy.uncache()
```
was change to 
```
fullFilenamePathOfChannel = listOfFilepathsToEachChannelOfEachPatient[index_of_wanted_image][channel_i]
f = h5py.File(fullFilenamePathOfChannel,'r')
channelData = f.get('lungData')
channelData = np.array(channelData, dtype='float32')
channelData=np.transpose(channelData, (2, 1, 0))
```
and I import the h5py on the begining of `trainValidateTestVisualiseParallel.py` by
`import numpy as np, h5py`

But some strange problems occurred.
I sucessfully loaded the data in the first epoch, but failed in the second epoch.
The error is `NameError: global name 'h5py' is not defined`. But I did import it, otherwise I could not load the data in the first epoch.

Besides, when I use Spyder to open the code, the incident is strange(not aligned. It is normal for other's code cloned from github). It is ok for gedit. Of course, it does not affect anything.




```
===========       NEW TRAINING SESSION         ===============
=============================================================
=============== PARAMETERS FOR THIS SESSION =================
=============================================================
Session's name = trainSessionFLtinyCnn_matData
CNN model's name = FLtinyCnn_matData
CNN model was loaded from = /mnt/disk1/Fu/Function/deepmedic/examples/output/cnnModels/FLtinyCnn_matData.initial.2016-11-04.10.29.19.506351.save
~~Output~~
Main output folder = /mnt/disk1/Fu/Function/deepmedic/examples/output
Path and filename to save trained models = /mnt/disk1/Fu/Function/deepmedic/examples/output/cnnModels//trainSessionFLtinyCnn_matData//FLtinyCnn_matData.trainSessionFLtinyCnn_matData
~~~~~~~~~~~~~~~~~~Generic Information~~~~~~~~~~~~~~~~
Number of Classes (incl. background) (from cnnModel) = 2
Number of Channels (Normal Pathway) (from cnnModel) = 1
Number of Cases for Training = 2
Number of Cases for Validation = 0
~~~~~~~~~~~~~~~~~~Training parameters~~~~~~~~~~~~~~~~
Filepaths to Channels of the Training Cases = [['/mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat1/lungData.mat'], ['/mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat2/lungData.mat']]
Filepaths to Ground-Truth labels of the Training Cases = ['/mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat1/lungLabel.mat', '/mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat2/lungLabel.mat']
~~Sampling~~
Region-Of-Interest Masks provided = True
Filepaths to ROI Masks of the Training Cases = ['/mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat1/lungMask.mat', '/mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat2/lungMask.mat']
~~Advanced Sampling~~
Using default sampling = True. NOTE: Adv.Sampl.Params are auto-set to perform default sampling if True.
Type of Sampling = Fore/Background (0)
Sampling Categories = ['Foreground', 'Background']
Percent of Samples to extract per Sampling Category = [ 0.5  0.5]
Provided Weight-Maps, pointing where to focus sampling for each category (if False, samples will be extracted based on GT and ROI) = False
Paths to weight-maps for sampling of each category = None
~~Training Cycle~~
Number of Epochs = 2
Number of Subepochs per epoch = 2
Number of cases to load per Subepoch (for extracting the samples for this subepoch) = 50
Number of Segments loaded on GPU per subepoch for Training = 1000. NOTE: This number of segments divided by the batch-size defines the number of optimization-iterations that will be performed every subepoch!
~~Learning Rate Schedule~~
Schedule Type: Stable (0), Auto (1), Predefined (2), Exponential (3) = 3
[Stable/Auto/Predefined] When decreasing Learning Rate, divide LR by = 2.0
[Stable/Auto] Wait that many epochs before lowering LR = 3
[Auto] Minimum increase in validation accuracy (0. to 1.) that resets the waiting counter = 0.0005
[Predefined] Predefined Schedule of Epochs when the LR will be lowered = None
[Exponential] [Number of initial epochs to not change LR and Mom, final value of LR, final value of Momentum] = [1, 0.00390625, 0.9]
~~Data Augmentation During Training~~
Reflect images per axis = [True, False, False]
Perform intensity-augmentation [I'= (I+shift)*mult] = False
[Int. Augm.] Sample Shift from N(mu,std) = []
[Int. Augm.] Sample Multi from N(mu,std) = []
[Int. Augm.] (DEBUGGING:) full parameters [no(0)/images(1)/segms(2), nonNorm(0)/norm(1), shift, mult] = [0, 'plcholder', [], []]
~~~~~~~~~~~~~~~~~~Validation parameters~~~~~~~~~~~~~~~~
Perform Validation on Samples throughout training? = False
Perform Full Inference on validation cases every few epochs? = False
Filepaths to Channels of the Validation Cases (Req for either of the above) = []
Provided Ground-Truth for Validation = False. NOTE: Required for Val on samples. Not Req for Full-Inference, but DSC will be reported if provided.
Filepaths to Ground-Truth labels of the Validation Cases = []
Provided ROI masks for Validation = False. NOTE: Validation-sampling and Full-Inference will be limited within this mask if provided. If not provided, Negative Validation samples will be extracted from whole volume, except if advanced-sampling is enabled, and the user provided separate weight-maps for sampling.
Filepaths to ROI masks for Validation Cases = []
~~~~~~~Validation on Samples throughout Training~~~~~~~
Number of Segments loaded on GPU per subepoch for Validation = 3000
~~Advanced Sampling~~
Using default uniform sampling for validation = True. NOTE: Adv.Sampl.Params are auto-set to perform uniform-sampling if True.
Type of Sampling = Uniform (1)
Sampling Categories = ['Uniform']
Percent of Samples to extract per Sampling Category = [1.0]
Provided Weight-Maps, pointing where to focus sampling for each category (if False, samples will be extracted based on GT and ROI) = False
Paths to weight-maps for sampling of each category = None
~~~~~Validation with Full Inference on Validation Cases~~~~~
Perform Full-Inference on Val. cases every that many epochs = 1
~~Predictions (segmentations and prob maps on val. cases)~~
Save Segmentations = True
Save Probability Maps for each class = [True, True]
Filepaths to save results per case = []
~~Feature Maps~~
Save Feature Maps = False
Save FMs in a 4D-image = False
Min/Max Indices of FMs to visualise per pathway-type and per layer = [[], [], [], []]
Filepaths to save FMs per case = []
~~~~~~~~~~~~~~~~~~Other Generic Parameters~~~~~~~~~~~~~~~~
~~Pre Processing~~
Pad Input Images = True
========== Done with printing session's parameters ==========
=============================================================
=======================================================
============== Training the CNN model =================
=======================================================
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~Starting new Epoch! Epoch #0/2 ~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
**************************************************************************************************
************* Starting new Subepoch: #0/2 *************
**************************************************************************************************
:=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Training... :=:=:=:=:=:=:=:=:
Out of [2] subjects given for [Training], it was specified to extract Segments from maximum [50] per subepoch.
Shuffled indices of subjects that were randomly chosen: [1, 0]
SAMPLING: Starting iterations to extract Segments from each subject for next Training...
SAMPLING: Going to load the images and extract segments from the subject #1/2
Loading subject with 1st channel at: /mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat2/lungData.mat
DEBUG: Index of this case in the original user-defined list of subjects: 1
Images for subject loaded.
From subject #0, sampling that many segments of Category [Foreground] : 250
Finished sampling segments of Category [Foreground]. Number sampled: 250
From subject #0, sampling that many segments of Category [Background] : 250
Finished sampling segments of Category [Background]. Number sampled: 250
SAMPLING: Going to load the images and extract segments from the subject #2/2
Loading subject with 1st channel at: /mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat1/lungData.mat
DEBUG: Index of this case in the original user-defined list of subjects: 0
Images for subject loaded.
From subject #1, sampling that many segments of Category [Foreground] : 250
Finished sampling segments of Category [Foreground]. Number sampled: 250
From subject #1, sampling that many segments of Category [Background] : 250
Finished sampling segments of Category [Background]. Number sampled: 250
TIMING: Extracting all the Segments for next Training took time: 2.808087(s)
:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Training. :=:=:=:=:=:=:=:=:
Loading Training data for subepoch #0 on shared variable...
TIMING: Loading sharedVariables for Training in epoch|subepoch=0|0 took time: 0.022822(s)
PARALLEL: Before Training in subepoch #0, submitting the parallel job for extracting Segments for the next Training.
-T-T-T-T-T- Now Training for this subepoch... This may take a few minutes... -T-T-T-T-T-
Trained on 0/100 of the batches for this subepoch...
Trained on 20/100 of the batches for this subepoch...
Trained on 40/100 of the batches for this subepoch...
Trained on 60/100 of the batches for this subepoch...
Trained on 80/100 of the batches for this subepoch...
+++++++++++++++++++++++ Reporting Accuracy over whole subepoch +++++++++++++++++++++++
TRAINING: Epoch #0, Subepoch #0, Overall:        mean accuracy:         0.8191  => Correctly-Classified-Voxels/All-Predicted-Voxels = 5618421/6859000
TRAINING: Epoch #0, Subepoch #0, Overall:        mean cost:             0.58442
+++++++++++++++ Reporting Accuracy over whole subepoch for Class-0 ++++++++ [Whole Foreground (Pos) Vs Background (Neg)] ++++++++++++++++
TRAINING: Epoch #0, Subepoch #0, Class-0:        mean accuracy:         0.8191  => (TruePos+TrueNeg)/All-Predicted-Voxels = 5618421/6859000
TRAINING: Epoch #0, Subepoch #0, Class-0:        mean sensitivity:      0.7917  => TruePos/RealPos = 1147560/1449548
TRAINING: Epoch #0, Subepoch #0, Class-0:        mean specificity:      0.8265  => TrueNeg/RealNeg = 4470861/5409452
TRAINING: Epoch #0, Subepoch #0, Class-0:        mean Dice:             0.6491
+++++++++++++++ Reporting Accuracy over whole subepoch for Class-1 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #0, Subepoch #0, Class-1:        mean accuracy:         0.8191  => (TruePos+TrueNeg)/All-Predicted-Voxels = 5618421/6859000
TRAINING: Epoch #0, Subepoch #0, Class-1:        mean sensitivity:      0.7917  => TruePos/RealPos = 1147560/1449548
TRAINING: Epoch #0, Subepoch #0, Class-1:        mean specificity:      0.8265  => TrueNeg/RealNeg = 4470861/5409452
TRAINING: Epoch #0, Subepoch #0, Class-1:        mean Dice:             0.6491
TIMING: Training on the batches of this subepoch #0 took time: 13.442058(s)
**************************************************************************************************
************* Starting new Subepoch: #1/2 *************
**************************************************************************************************
:=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Training... :=:=:=:=:=:=:=:=:
Out of [2] subjects given for [Training], it was specified to extract Segments from maximum [50] per subepoch.
Shuffled indices of subjects that were randomly chosen: [0, 1]
SAMPLING: Starting iterations to extract Segments from each subject for next Training...
SAMPLING: Going to load the images and extract segments from the subject #1/2
Loading subject with 1st channel at: /mnt/disk1/Fu/Function/deepmedic/examples/dataForExamples/FL_TestMat/train/mat1/lungData.mat
An error has occured during the function execution
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 90, in run
    __result = __f(*__args)
  File "<string>", line 107, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
  File "<string>", line 78, in actual_load_patient_images_from_filepath_and_return_nparrays
NameError: global name 'h5py' is not defined**
Traceback (most recent call last):
  File "./deepMedicRun", line 102, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/mnt/disk1/Fu/Function/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 449, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/mnt/disk1/Fu/Function/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1322, in do_training
    subsampledImagePartsChannelsToLoadOnGpuForSubepochTraining] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable
```

Thank you.

**Comment by Kamnitsask** [comment] 2016-11-04 12:19
Hello Carol,

Good stuff, you are almost done.

The problem is that the library that I use for parallel processing needs to be given the new import. For the parallel process (that extracts training samples for the 2nd epoch, while the 1st training is performed on the gpu) to load h5py.

in trainValidationTestParallel.py, find the line:
tupleWithModulesToImportWhichAreUsedByTheJobFunctions = (........)
There, inside the parenthesis, add "h5py".

I believe it should then work.

Let me know how it goes.

K
